stages:
  - test

test:
  image: node:latest
  stage: test
  script:
    ## install dependencies
    - apt update && apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    #- npm install cypress
    #- npm ci 
    ## start the server in the background
    #- npm run start:ci &
    ## run Cypress tests
    #- npx cypress run