image: cypress/included:7.4.0

stages:
  - test
test:
  stage: test
  script:
    - npm i -f
    # install dependencies
    - npm ci 
    # start the server in the background
    - npm run start:ci &
    # run Cypress tests
    - npx cypress run