image: cypress/base:12

stages:
  - test
test:
  stage: test
  script:
    # install dependencies
    - npm ci 
    # start the server in the background
    - npm run start:ci &
    # run Cypress tests
    - npx cypress run